config/routes.rb
Uctads::Application.routes.draw do

  # == categories routing ==
  get '/categories',          to: 'categories#index',   as: 'categories'
  get '/categories/new',      to: 'categories#new',     as: 'new_category'
  post '/categories',         to: 'categories#create',  as: 'create_category'
  get '/categories/:id',      to: 'categories#show',    as: 'show_category'
  get '/categories/:id/edit', to: 'categories#edit',    as: 'edit_category'
  patch '/categories/:id',    to: 'categories#update',  as: 'update_category'
  delete '/categories/:id',   to: 'categories#destroy', as: 'destroy_category'

  get '/categories/:id/ancestor_fields', to: 'categories#ancestor_fields'

  # == adverts routing ==
  get     '/adverts',                 to: 'adverts#index',              as: 'adverts'
  get     '/adverts_by_category/:id', to: 'adverts#index_by_category',  as: 'adverts_by_category'
  post    '/adverts',                 to: 'adverts#create',             as: 'create_advert'
  get     '/adverts/new',             to: 'adverts#new',                as: 'new_advert'
  get     '/adverts/:id',             to: 'adverts#show',               as: 'show_advert'
  get     '/adverts/:id/edit',        to: 'adverts#edit',               as: 'edit_advert'
  patch   '/adverts/:id',             to: 'adverts#update',             as: 'update_advert'
  delete  '/adverts/:id',             to: 'adverts#destroy',            as: 'destroy_advert'
  post    '/adverts/new_ad_form',     to: 'adverts#new_ad_form',        as: 'new_ad_form_advert'

  get     '/adverts/:id/gallery/edit',    to: 'adverts#edit_gallery',       as: 'edit_gallery'
  post    '/adverts/:id/gallery/upload', to: 'adverts#upload_to_gallery', as: 'upload_to_gallery'

  # == uploads routing ==
  get     '/uploads/:id',       to: 'uploads#show',     as: 'show_upload'
  get     '/uploads/:id/edit',  to: 'uploads#edit',     as: 'edit_upload'
  patch   '/uploads/:id',       to: 'uploads#update',   as: 'update_upload'
  delete  '/uploads/:id',       to: 'uploads#destroy',  as: 'destroy_upload'

  root 'adverts#index'


end

app/models/advert.rb
class Advert < ActiveRecord::Base
  include PgSearch

  belongs_to :category
  has_many :uploads

  serialize :fieldvalues, Hash

  validate :title_must_be_valid, :description_must_be_valid, :all_fields_must_match_fielddefs, :price_must_be_valid

  pg_search_scope :search_full_text, :against => {
    title: 'A',
    description: 'B',
  }

  PRICE_TYPES = {'exact' => 'Exact Price', 'poa' => 'On Application', 'swap' => 'To Swap', 'free' => 'Free'}

  # -- model validation

  def title_must_be_valid
    if not title.present?
      errors.add(:title, 'Advert title cannot be blank')
    elsif title.length < 5 or title.length > 60
      errors.add(:title, 'Advert title must be between 5 and 60 characters')
    end
  end

  def description_must_be_valid
    if not description.present?
      errors.add(:description, 'Advert must have a description')
    elsif description.length < 10 or description.length > 10000
      errors.add(:description, 'Advert description must be longer than 10 characters')
    end
  end

  def all_fields_must_match_fielddefs
    fielddefs = category.self_and_ancestors.map {|p| p.fields}.inject {|a,b| a.merge!(b)}

    # check extra fields
    extras = fieldvalues.keys - fielddefs.keys
    if not extras.empty?
      errors.add(:fieldvalues, "Unknown fields (#{extras.join(', ')})")
    end

    fielddefs.each_pair do |name, options|
      if fieldvalues.include? name and fieldvalues[name].present?
        if options.include? :select and not options[:select].include? fieldvalues[name]
          errors.add(:fieldvalues, "Field '#{name}' must be one of #{options[:select].join(', ')}")
        end
      elsif not options[:optional]
        errors.add(:fieldvalues, "Field '#{name}' is required")
      end
    end
  end

  def price_must_be_valid
    if not PRICE_TYPES.include? price_type
      errors.add(:price_type, "Price type #{price_type} is invalid")
    end
    if price_type == 'exact' and (price.nil? or price < 0.00 or price > 99999999.99)
      errors.add(:price, "Price value '#{price}' is out of the allowed range")
    end
  end

end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController

  def index


    if params[:search]
      @was_search = true
      @search_text = params[:search]
      @adverts = Advert.search_full_text(params[:search])
    else
      @was_search = false
      @adverts = Advert.order(created_at: :desc)
    end


    #nested category tree
    @category_tree = {}

    # roots are always shown in the list
    Category.roots.each {|r| @category_tree[r] = {}}
  end

  def index_by_category
    @selected_category = Category.find(params[:id])

    @category_tree = @selected_category.root.hash_tree

    # roots are always shown in the list
    Category.roots.each do |r|
      unless @category_tree.has_key? r
        @category_tree[r] = {}
      end
    end

    ids = @selected_category.self_and_descendant_ids

    @adverts = Advert.where(category_id: ids).order(created_at: :desc)
  end

  def new
    @advert = Advert.new
    @categories = Category.hash_tree
  end

  def new_ad_form
    category = Category.find(advert_category_param[:category_id])
    @advert = Advert.new
    @advert.category = category
    @fieldsdef = category.self_and_ancestors.map {|p| p.fields}.inject {|a,b| a.merge!(b)}
  end

  def create
    @advert = Advert.new(advert_form_params)
    if @advert.save
        redirect_to edit_gallery_path(@advert), notice: "Advert successfully created."
    else
        @fieldsdef = @advert.category.self_and_ancestors.map {|p| p.fields}.inject {|a,b| a.merge!(b)}
        render action: 'new_ad_form'
    end
  end

  def show
    @advert = Advert.find(params[:id])
    @images = @advert.uploads
    @breadcrumb = @advert.category.ancestors.reverse + [@advert.category]
  end

  def edit
    @advert = Advert.find(params[:id])
    @fieldsdef = @advert.category.self_and_ancestors.map {|p| p.fields}.inject {|a,b| a.merge!(b)}
  end

  def update
    @advert = Advert.find(params[:id])
    if @advert.update_attributes(advert_form_params)
      redirect_to show_advert_path(@advert), notice: "Advert successfully updated."
    else
      @fieldsdef = @advert.category.self_and_ancestors.map {|p| p.fields}.inject {|a,b| a.merge!(b)}
      render action: 'edit'
    end
  end

  def destroy
    advert = Advert.find(params[:id])

    advert.delete
    redirect_to adverts_path, notice: "'Advert #{advert.title}' removed."
  end

  def edit_gallery
    @advert = Advert.find(params[:id])
    @uploads = Upload.where(advert_id: params[:id])

    @upload_max = Upload.MAX_PER_ADVERT
    @upload_count = @uploads.length
    @upload_percent = ((@upload_count / @upload_max.to_f) * 100).to_i

    if @upload_count < @upload_max
      @new_upload = Upload.new
      @new_upload.advert = @advert
    else
      @new_upload = nil
    end
  end

  def upload_to_gallery
    @upload = Upload.new(upload_params)
    if @upload.save
      redirect_to edit_gallery_path(@upload.advert), notice: 'Image Uploaded!'
    else
      redirect_to edit_gallery_path(@upload.advert), alert: "Upload Failed. #{get_error_string(@upload)}"
    end
  end

  def search

  end

  private

    def advert_category_param
      params.require(:advert).permit(:category_id)
    end

    def advert_form_params
      r = params.require(:advert).permit(:title, :description, :fieldvalues, :category_id, :price, :price_type)
      r['fieldvalues'] = JSON.parse(r['fieldvalues'])
      return r
    end

    def upload_params
      params.require(:upload).permit(:image, :advert_id)
    end

    def get_error_string(obj)
      obj.errors.map {|a, e| "#{a} : #{e}. "}.join
    end
end

app/helpers/adverts_helper.rb
module AdvertsHelper

  def nested_categories_tree(categories)
    li_s = []

    categories.keys.each do |k|
      content = content_tag(:i, nil, {class: 'fa fa-angle-right', style: 'padding-right: 10px;'})
      content = link_to( content + k.name, 'javascript:void(0);', onclick: 'AdvertStageOneBuilder.next('+k.id.to_s+')')
      content = content_tag(:div, content, {class: 'panel-heading panel-heading-sm'}) + nested_categories_tree(categories[k])
      content = content_tag(:li, content, {class: 'panel panel-default', style: 'margin: 5px 5px 5px 0px;'})
      li_s << content
    end

    content_tag(:ul, li_s.join.html_safe)
  end

  def build_side_bar(categories, selected=nil)
    style = selected.nil? ? 'font-weight: bold' : ''
    content = content_tag(:span, nil) + link_to("All", adverts_path, style: style)
    content = content_tag(:div, content)
    content = content_tag(:li, content)
    html = content_tag(:ul, content.html_safe, class: 'sidebar-categories')

    html += build_side_bar_tree(categories, selected)

    html
  end

  def build_side_bar_tree(categories, selected=nil)
    li_s = []

    categories.keys.sort_by {|k| k.name }.each do |k|
      style = (selected.nil? or k.id != selected) ? '' : 'font-weight: bold'
      content = content_tag(:span, nil) + link_to(k.name, adverts_by_category_path(k), style: style)
      content = content_tag(:div, content) + build_side_bar_tree(categories[k], selected)
      content = content_tag(:li, content)
      li_s << content
    end

    content_tag(:ul, li_s.join.html_safe, class: 'sidebar-categories')
  end

  def format_number_rands(n)
    number_to_currency(n, unit: 'R', precision: 0, delimiter: ',')
  end

  def format_number_cents(n)
    n = n % 1
    "." + (n % 1 * 100).round.to_i.to_s.rjust(2, '0')
  end

  def format_number_pretty(n)
    number_to_currency(n, unit: 'R', precision: ((n%1) > 0.001) ? 2 : 0, delimiter: ',')
  end

end

app/views/adverts/_adverts_table.html.haml
.col-sm-9
  .panel.panel-default
    .panel-heading.item-heading{style: 'background-color: #E3ECF3'}
      = "Ads"
    .table-responsive.adverts-table
      %table.table.table-bordered
        %col{style: "width: 120px"}
        %col
        %col{style: "width: 10%"}
        %tbody
          - if @adverts.count(:all) == 0
            %tr
              %td.text-center{colspan: 3}
                %p
                  %i.fa.fa-frown-o
                  = "Oops, no ads have been posted"
                %p
                  = "Change this by "
                  = link_to "posting a new ad!", new_advert_path

          - else
            - @adverts.each do |advert|
              %tr
                %td.text-center{style: "vertical-align: middle;"}
                  - first_image = advert.uploads.take
                  - unless first_image.nil?
                    = link_to image_tag(first_image.image.url(:thumb), class: 'img-bordered', style: 'min-width: 80px;'), show_advert_path(advert)
                  - else
                    %h3
                      %i.fa.fa-photo

                %td
                  = link_to advert.title, show_advert_path(advert)
                  %p.advert-description
                    = text_truncate advert.description, 200
                  %small.text-muted
                    %em
                      = "Posted #{time_ago_in_words(advert.created_at)} ago :"
                      = link_to advert.category.name, adverts_by_category_path(advert.category)
                %td.text-center{style: "vertical-align: middle;"}
                  %h4
                    - if advert.price_type == 'exact'
                      = format_number_pretty(advert.price)
                    - else
                      = Advert::PRICE_TYPES[advert.price_type]

app/views/adverts/_form.html.haml
:css
  .required-label:after {
    content: " *";
    color: #F00;
    font-weight: bold;
  }

#form-wrapper
  = form_for @advert, url: (@advert.id.nil? ? create_advert_path(@advert) : update_advert_path(@advert)), html: {class: 'form-horizontal'} do |f|
    = f.hidden_field :fieldvalues, value: @advert.fieldvalues.to_json
    = f.hidden_field :category_id, value: @advert.category_id
    .form-group
      = f.label :title, class: 'col-sm-2 control-label required-label'
      .col-sm-10
        = f.text_field :title, class: 'form-control'

    .form-group
      %label.col-sm-2.control-label Category
      .col-sm-6
        %p.form-control-static= @advert.category.name

    .form-group
      = f.label :description, class: 'col-sm-2 control-label required-label'
      .col-sm-10
        = f.text_area :description, class: 'form-control', rows: 8

    .form-group
      = f.label :price, class: 'col-sm-2 control-label required-label'
      .col-sm-3{style:'width: auto; margin-bottom: 10px;'}
        = f.select :price_type, (Advert::PRICE_TYPES.map {|k,v| [v,k]}), {}, {class: 'form-control better-select-box', onChange: 'AdvertStageTwoBuilder.updatePriceField()'}
      #price-field-wrapper.col-sm-3
        .input-group{style: 'margin-bottom:10px;'}
          %span#exact-price-field.input-group-addon{style: 'background-color: #EEE;'} R
          = f.text_field :price, {data: {role: 'money', a_sep: '', a_dec: '.'}, class: 'form-control', placeholder: '0.00'}

    - if not @fieldsdef.empty?
      .form-group
        %label.col-sm-2.control-label Essentials
        .col-sm-10
          .form-group
            - @fieldsdef.each_pair do |name,ops|
              .col-sm-5
                .input-group{style: 'margin-bottom:10px;'}
                  %span.input-group-addon{style: 'background-color: #EEE;'}
                    %strong{class: (ops[:optional] ? '' : 'required-label')}= name
                    - if ops[:optional]
                      %i (Optional)
                  - if ops[:select]
                    %select.form-control.better-select-box.field-value-input{id: "field_#{name}", name: name}
                      %option= ''
                      - ops[:select].each do |i|
                        %option= i
                  - else
                    %input.form-control.field-value-input{type: 'text', value: '', name: name, id: "field_#{name.sub(' ', '__')}"}

    .clearfix
    .form-group
      .col-sm-2
      .col-sm-10
        %p{style: 'color: #F00'}= "* indicates a required field"

    - if not @advert.errors.empty?
      .form-group
        .col-sm-2
        .col-sm-10
          - @advert.errors.each do |attribute, error|
            .alert.alert-danger.alert-dismissable
              %button.close{type: 'button', 'data-dismiss' => 'alert', 'aria-hidden' => 'true'}
                &times;
              = error

    .form-group
      .col-sm-12
        .pull-right
          = link_to 'Save', 'javascript:void(0);', onclick: 'AdvertStageTwoBuilder.submit()', class: 'btn btn-success'
          = link_to 'Back', new_advert_path, class: 'btn btn-info'
          = link_to 'Cancel', adverts_path, class: 'btn btn-default'

= javascript_include_tag 'autoNumeric'
= javascript_include_tag 'advert_stage_two'

:javascript
  $(document).ready(function(){
    var moneyfield = $('input[data-role=money]')
    moneyfield.autoNumeric('init')
    moneyfield.keydown(function(event){
      if(event.keyCode == 13) $(this).autoNumeric('set', $(this).autoNumeric('get'))
    });
    AdvertStageTwoBuilder.fillvalues();
    AdvertStageTwoBuilder.updatePriceField();
  });

app/views/adverts/edit.html.haml
- title 'Edit Advert'

.page-header
  %h2
    Edit Advert
    %small= @advert.category.name

= render 'form'

app/views/adverts/edit_gallery.html.haml
- title 'Edit Gallery'

.page-header
  %h2
    = 'Edit Gallery'

= render 'layouts/messages'

.progress-label
  = "#{@upload_count} / #{@upload_max} images :"
.progress.progress-striped
  .progress-bar.progress-bar-info{role: 'progressbar', aria: {valuenow: @upload_count, valuemin: 0, valuemax: @upload_max}, style: "width: #{@upload_percent}%"}


- unless @uploads.empty?
  .panel.panel-default
    .panel-heading.item-heading{style: 'background-color: #E3ECF3'}
      = "Images"
    .table-responsive
      %table.table.table-bordered
        %col{style: "width: 120px"}
        %col
        %col{style: "width: 50px"}
        %tbody
          - @uploads.each do |upload|
            %tr
              %td
                = link_to image_tag(upload.image.url(:thumb), class: 'img-bordered'), show_upload_path(upload)
              %td
                %p.paragraph-heading
                  Description
                %p
                  = upload.description
                %p
                  %small
                    = link_to "(edit description)", edit_upload_path(upload)
              %td
                = link_to fa_icon('trash-o'), destroy_upload_path(upload), method: :delete, data: {confirm: 'Are you sure you want to delete the image?'}, class: 'btn btn-warning btn-block'

- unless @new_upload.nil?
  = form_for @new_upload, url: upload_to_gallery_path, html: {class: 'form-horizontal'} do |f|
    = f.hidden_field :advert_id, value: @new_upload.advert_id
    .panel.panel-default
      .panel-heading.item-heading{style: 'background-color: #E3ECF3'}
        = "Add another image"
      %table.table.table-bordered
        %tbody
          %tr
            %td
              = f.file_field :image, accept: 'image/png,image/gif,image/jpeg', style: 'padding: 5px; width: 100%'
            %td
              = f.submit 'Upload', class: 'btn btn-info btn-sm btn-block'

= link_to "Back to Advert", show_advert_path(@advert), class: 'btn btn-default btn-sm pull-right'

app/views/adverts/index.html.haml
- title 'Adverts'

.page-header
  %h2
    = "Adverts"

- if @was_search
  %p
    = "You searched for '#{@search_text}'"

.row
  .col-sm-3
    .panel.panel-default
      .panel-heading.item-heading{style: 'background-color: #E3ECF3'}
        Categories
      .panel-body
        = build_side_bar(@category_tree)

  = render 'adverts_table'

app/views/adverts/index_by_category.html.haml
- title @selected_category.name

.page-header
  %h2
    = @selected_category.name

.row
  .col-sm-3
    .panel.panel-default
      .panel-heading.item-heading{style: 'background-color: #E3ECF3'}
        Categories
      .panel-body
        = build_side_bar(@category_tree, @selected_category.id)

  = render 'adverts_table'

app/views/adverts/new.html.haml
- title 'New Advert'

:css
  ul {
    list-style: none;
  }
  #top-nest-lvl > ul{
    padding-left: 0px;
    margin-left: 0px;
  }

.page-header
  %h2
    New Advert
    %small Choose a Category

#top-nest-lvl.col-sm-10
  %p
    Pick a category for your Ad, remember that the more specific a category you
    choose the easier it will be for someone to find it. If you want to suggest
    a new category, or a modification to one, use
    %a
      this
    form.

  = nested_categories_tree(@categories)

  #form_wrapper
    = form_for @advert, url: new_ad_form_advert_path(@advert) do |f|
      = f.hidden_field :category_id

= javascript_include_tag 'advert_stage_one'

app/views/adverts/new_ad_form.html.haml
- title 'New Advert'

.page-header
  %h2
    New Advert
    %small= @advert.category.name

= render 'form'

app/views/adverts/show.html.haml
- title @advert.title

%ul.breadcrumb{style: "margin-top:10px;"}
  %li
    = link_to 'Adverts', adverts_path
  - @breadcrumb.each do |b|
    %li
      = link_to b.name, adverts_by_category_path(b)

.page-header
  %h2
    = @advert.title
    %small.pull-right
      %p
        %i.fa.fa-clock-o
        = "#{time_ago_in_words(@advert.created_at)} ago"

.row
  .col-sm-9
    %ul.list-group
      %li.list-group-item.item-heading
        = "Images"
        = link_to "(edit)", edit_gallery_path(@advert)
      %li.list-group-item.text-center
        - if @images.empty?
          .missing-images-text
            = "(No images added)"
        - else
          - @images.each do |image|
            = link_to image_tag(image.image.url(:thumb), {class: 'img-bordered', title: image.description}), show_upload_path(image)

      %li.list-group-item.item-heading
        = "Description"
      %li.list-group-item.padding-2
        .padding-5
          = raw simple_format @advert.description
      - if @advert.fieldvalues.length > 0
        %li.list-group-item.item-heading
          = "Fields"
        %li.list-group-item.padding-2
          .row.no-margin
            - @advert.fieldvalues.each_pair do |name, value|
              .col-sm-5.padding-2
                .input-group.advert-field
                  %span.input-group-addon
                    %strong= name
                  .form-control= value

  .col-sm-3
    .panel.panel-default
      - if @advert.price_type == 'exact'
        %h1.text-center{style: 'margin: 10px 20px;'}
          = format_number_rands(@advert.price) + "<small>".html_safe + format_number_cents(@advert.price) + "</small>".html_safe
      - else
        %h3.text-center{style: 'margin: 10px 20px;'}
          = Advert::PRICE_TYPES[@advert.price_type]

    .well
      = "Contact area"
    .row.no-margin
      .col-sm-6.padding-2
        = link_to 'Edit', edit_advert_path(@advert), {class: 'btn btn-info', style: 'width: 100%; margin-bottom: 20px'}
      .col-sm-6.padding-2
        = link_to('Delete', {controller: 'adverts', action: 'destroy', id: @advert.id}, {data: {confirm: 'Are you sure you want to delete this advert?'}, :method => :delete, class: 'btn btn-danger', style: 'width: 100%; margin-bottom: 20px'})