config/routes.rb
Uctads::Application.routes.draw do

  # == categories routing ==
  get '/categories',          to: 'categories#index',   as: 'categories'
  get '/categories/new',      to: 'categories#new',     as: 'new_category'
  post '/categories',         to: 'categories#create',  as: 'create_category'
  get '/categories/:id',      to: 'categories#show',    as: 'show_category'
  get '/categories/:id/edit', to: 'categories#edit',    as: 'edit_category'
  patch '/categories/:id',    to: 'categories#update',  as: 'update_category'
  delete '/categories/:id',   to: 'categories#destroy', as: 'destroy_category'

  get '/categories/:id/ancestor_fields', to: 'categories#ancestor_fields'

  # == adverts routing ==
  get     '/adverts',                 to: 'adverts#index',              as: 'adverts'
  get     '/adverts_by_category/:id', to: 'adverts#index_by_category',  as: 'adverts_by_category'
  post    '/adverts',                 to: 'adverts#create',             as: 'create_advert'
  get     '/adverts/new',             to: 'adverts#new',                as: 'new_advert'
  get     '/adverts/:id',             to: 'adverts#show',               as: 'show_advert'
  get     '/adverts/:id/edit',        to: 'adverts#edit',               as: 'edit_advert'
  patch   '/adverts/:id',             to: 'adverts#update',             as: 'update_advert'
  delete  '/adverts/:id',             to: 'adverts#destroy',            as: 'destroy_advert'
  post    '/adverts/new_ad_form',     to: 'adverts#new_ad_form',        as: 'new_ad_form_advert'

  get     '/adverts/:id/gallery/edit',    to: 'adverts#edit_gallery',       as: 'edit_gallery'
  post    '/adverts/:id/gallery/upload', to: 'adverts#upload_to_gallery', as: 'upload_to_gallery'

  # == uploads routing ==
  get     '/uploads/:id',       to: 'uploads#show',     as: 'show_upload'
  get     '/uploads/:id/edit',  to: 'uploads#edit',     as: 'edit_upload'
  patch   '/uploads/:id',       to: 'uploads#update',   as: 'update_upload'
  delete  '/uploads/:id',       to: 'uploads#destroy',  as: 'destroy_upload'

  root 'adverts#index'


end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_tree :order => 'name'

  has_many :adverts

  serialize :fields, Hash

  validates :name, presence: {message: 'Category name cannot be blank'}
  validate :cant_have_dupl_name, :cant_have_conflicting_fields

  def build_fields_hash
    f = fields.nil? ? {} : fields
    ancestors.each do |a|
      f = a.fields.merge(f)
    end
    return f
  end

  def cant_have_dupl_name
    if siblings.index {|s| s.name == name}
      errors.add(:name, 'Name conflicts with an adjacent category in the tree!')
    end
  end

  def cant_have_conflicting_fields
    # duplicate field names
    dups = fields.keys - fields.keys.uniq
    if not dups.empty?
      errors.add(:fields, "Duplicate field names! (#{dups.join(' ')})")
    end

    # test ancestor fields
    conflicts = ancestors.map {|a| a.fields.keys}.flatten & fields.keys
    if not conflicts.empty?
      errors.add(:fields, "Fields conflict with parent fields! (#{conflicts.join(' ')})")
    end

    # test descendants fields
    descendants.each do |d|
      conflicts = d.fields.keys & fields.keys
      if not conflicts.empty?
        errors.add(:fields, "Fields (#{conflicts.join(' ')}) conflict with descendant #{d.name}")
      end
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.hash_tree
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
    @parents = build_parent_tree(tree_without_self(@category), nil, 0)
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to show_category_path(@category), notice: "Category '#{@category.name}' successfully updated."
    else
      @parents = build_parent_tree(tree_without_self(@category), nil, 0)
      render action: 'edit'
    end
  end

  def new
    @category = Category.new
    @parents = build_parent_tree(Category.hash_tree, nil, 0)
  end

  def create
    @category = Category.new(category_params)
    @parents = build_parent_tree(Category.hash_tree, nil, 0)
    if @category.save
      redirect_to categories_path, notice: "Category '#{@category.name}' successfully created."
    else
      render action: 'new'
    end
  end

  def destroy
    category = Category.find(params[:id])

    ads = Advert.where(category_id: category.self_and_descendant_ids)
    if not ads.empty?
      redirect_to categories_path, error: "Category '#{category.name}' cannot be deleted because it contains #{ads.length} adverts"
    else
      children = category.descendants
      children.each do |c|
        c.delete
      end
      category.delete
      redirect_to categories_path, notice: "Category '#{category.name}' successfully deleted"
    end
  end

  def ancestor_fields
    category = Category.find(params[:id])
    render :text => category.ancestors.map {|a| a.fields.keys}.flatten.join(', ')
  end

  private
    def category_params
      r = params.require(:category).permit(:name, :fields, :parent_id)
      r['fields'] = JSON.parse(r['fields'])
      return r
    end

    def build_parent_tree(h, o, i)
      o = [] if not o
      h.each_pair do |k,v|
        k.name = '-'*i + k.name
        o.push(k)
        build_parent_tree(v, o, i+2)
      end
      return o
    end

    def tree_without_self(c)
      tree = Category.hash_tree
      t = tree
      if not c.parent.nil?
        c.ancestors.reverse_each do |c|
          t = t[c]
        end
      end
      t.except!(c)
      return tree
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper

  # Method to generate tree view of categories
  # This is faster than using recursive partical views.
  def nested_categories_view(categories)
    content_tag(:ul,
      categories.map do |category,children|
        content_tag(:li,
          content_tag(:div,
            content_tag(:i, nil, {class: 'fa fa-angle-right', style: 'padding-right: 10px; color: #666;'}) +
            link_to(category.name, show_category_path(category)) +
            " (#{category.fields.keys.sort.join(', ')})" +
            link_to(
              content_tag(:i, nil, {class: 'fa fa-trash-o'}), destroy_category_path(category),
                    :data => { confirm: 'Are you sure you want to delete this category and its children?' },
                    :method => :delete,
                    :action => :delete,
                    class: 'btn btn-danger btn-xs pull-right'), {class: 'panel-heading'}
          ) + content_tag(:div, '', {class: 'clearfix'}) + nested_categories_view(children),
        {class: 'panel panel-default', style: 'margin: 5px 5px 5px 0px;'})
      end.join.html_safe
    )
  end

end

app/views/categories/_form.html.haml
= javascript_include_tag 'category_builder'

#form-wrapper
  = form_for @category, url: (@category.id.nil? ? create_category_path : update_category_path), html: {class: 'form-horizontal'} do |f|
    = f.hidden_field :fields, value: @category.fields.to_json

    .form-group
      = f.label :name, class: 'control-label'
      = f.text_field :name, {class: 'form-control', style: 'width: 300px;', placeholder: 'Category name'}

    .form-group
      = f.label :parent_id, class: 'control-label'
      = f.collection_select :parent_id, @parents, :id, :name, {include_blank: "(No parent)"}, {class: 'form-control', style: 'width: 300px;', onChange: 'CategoryBuilder.getInheritedFields(this)'}
      %span#inherited-fields.help-block

    #category_builder_form_anchor

    - @category.errors.each do |attribute, error|
      .alert.alert-danger.alert-dismissable
        %button.close{type: 'button', 'data-dismiss' => 'alert', 'aria-hidden' => 'true'}
          &times;
        = error

    %p
      = link_to "Save", 'javascript:void(0);', {onclick: "CategoryBuilder.save();", class: 'btn btn-success'}
      = link_to 'Cancel', (@category.id.nil? ? categories_path : show_category_path), {class: 'btn btn-default'}

:javascript
  $(document).ready( function() {
    CategoryBuilder.create_form()
  });

app/views/categories/edit.html.haml
- title 'Edit Category'

.page-header
  %h2 Edit Category

.col-sm-12
  = render 'form'

app/views/categories/index.html.haml
- title 'Categories'

:css
  ul {
    list-style: none;
  }

  #top-nest-lvl > ul{
    padding-left: 0px;
    margin-left: 0px;
  }

.page-header
  %h2 Categories

= render 'layouts/messages'

#top-nest-lvl.col-sm-12
  = nested_categories_view(@categories)

  = link_to 'Add Category'.html_safe, new_category_path, {class: 'btn btn-success'}

app/views/categories/new.html.haml
- title 'New Category'

.page-header
  %h2 New Category

.col-sm-12
  = render 'form'

app/views/categories/show.html.haml
- title @category.name

.page-header
  %h2
    = @category.name
    %small
      = (@category.parent) ? "[category of #{@category.parent.name}]" : '[category]'

- fields = @category.fields.nil? ? {} : @category.fields

.col-sm-12
  %p
    %strong Inherits fields:
    = "(#{@category.ancestors.map {|a| a.fields.keys}.flatten.join(', ')})"

  .panel.panel-default
    .panel-heading
      .panel-title= "Category Fields (#{(fields.size > 0) ? fields.size : 'None'})"
    %ul.list-group
      - fields.each do |k, v|
        %li.list-group-item
          .row
            .col-sm-3{style: 'margin-bottom: 10px;'}
              %strong Field:
              = "'#{k}'"
              %i= v[:optional] ? '(Optional)' : '(Not Optional)'
          - if v.has_key?(:select)
            .row
              .col-sm-6
                .panel.panel-default{style: 'margin-bottom:0;'}
                  .panel-heading
                    .panel-title Selectable Items
                  %ul.list-group
                    - v[:select].each do |item|
                      %li.list-group-item{style: 'padding:3px'}
                        = item

  = link_to 'Edit', [:edit, @category], class: 'btn btn-info'
  = link_to 'Back', categories_path, class: 'btn btn-default'