config/routes.rb
Uctads::Application.routes.draw do

  # == categories routing ==
  get '/categories',          to: 'categories#index',   as: 'categories'
  get '/categories/new',      to: 'categories#new',     as: 'new_category'
  post '/categories',         to: 'categories#create',  as: 'create_category'
  get '/categories/:id',      to: 'categories#show',    as: 'show_category'
  get '/categories/:id/edit', to: 'categories#edit',    as: 'edit_category'
  patch '/categories/:id',    to: 'categories#update',  as: 'update_category'
  delete '/categories/:id',   to: 'categories#destroy', as: 'destroy_category'

  get '/categories/:id/ancestor_fields', to: 'categories#ancestor_fields'

  # == adverts routing ==
  get     '/adverts',                 to: 'adverts#index',              as: 'adverts'
  get     '/adverts_by_category/:id', to: 'adverts#index_by_category',  as: 'adverts_by_category'
  post    '/adverts',                 to: 'adverts#create',             as: 'create_advert'
  get     '/adverts/new',             to: 'adverts#new',                as: 'new_advert'
  get     '/adverts/:id',             to: 'adverts#show',               as: 'show_advert'
  get     '/adverts/:id/edit',        to: 'adverts#edit',               as: 'edit_advert'
  patch   '/adverts/:id',             to: 'adverts#update',             as: 'update_advert'
  delete  '/adverts/:id',             to: 'adverts#destroy',            as: 'destroy_advert'
  post    '/adverts/new_ad_form',     to: 'adverts#new_ad_form',        as: 'new_ad_form_advert'

  get     '/adverts/:id/gallery/edit',    to: 'adverts#edit_gallery',       as: 'edit_gallery'
  post    '/adverts/:id/gallery/upload', to: 'adverts#upload_to_gallery', as: 'upload_to_gallery'

  # == uploads routing ==
  get     '/uploads/:id',       to: 'uploads#show',     as: 'show_upload'
  get     '/uploads/:id/edit',  to: 'uploads#edit',     as: 'edit_upload'
  patch   '/uploads/:id',       to: 'uploads#update',   as: 'update_upload'
  delete  '/uploads/:id',       to: 'uploads#destroy',  as: 'destroy_upload'

  root 'adverts#index'


end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :advert

  has_attached_file :image, styles: {
    thumb: '100x100#',
    medium: '300x300#',
    original: '800x600>'
  }

  validates :image, presence: true
  validates_attachment_content_type :image, :content_type => /^image\/(png|jpeg|jpg)/
  validates_attachment_size :image, :in => 0.megabytes..2.megabytes
  validates :advert, presence: true
  validate :max_uploads_per_advert

  @@MAX_PER_ADVERT = 10
  def self.MAX_PER_ADVERT
    @@MAX_PER_ADVERT
  end

  def max_uploads_per_advert
    if advert.uploads.length > @@MAX_PER_ADVERT
        errors.add(:advert, "has too many images")
    end
  end


end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController

  def edit
    @upload = Upload.find(params[:id])
  end

  def show
    @upload = Upload.find(params[:id])
  end

  def update
    @upload = Upload.find(params[:id])
    if @upload.update_attributes(edit_upload_params)
      redirect_to edit_gallery_path(@upload.advert), notice: "Updated description of image."
    else
      render action: 'edit'
    end
  end

  def destroy
    upload = Upload.find(params[:id])
    upload.delete
    redirect_to edit_gallery_path(upload.advert), notice: "Image removed."
  end

  private
    def edit_upload_params
      params.require(:upload).permit(:description)
    end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/edit.html.haml
- title 'Edit Description'

.page-header
  %h2
    = 'Edit Description'

.row
  .col-sm-4
    %p.text-center
      = image_tag @upload.image.url(:medium), class: 'img-rounded'

  .col-sm-8
    = form_for @upload, url: update_upload_path(@upload) do |f|
      .form-group
        = f.text_area :description, class: 'form-control', rows: 4

      = f.submit 'Update Description', class: 'btn btn-primary btn-sm '
      = link_to "Cancel", edit_gallery_path(@upload.advert), class: 'btn btn-default btn-sm'

app/views/uploads/new.html.haml
- title 'New Upload'

.page-header
  %h2
    = 'New Upload'


#form-wrapper
  = form_for @upload, url: create_upload_path(@upload), html: {class: 'form-horizontal'} do |f|
    .form-group
      = f.label :image, class: 'control-label'
      = f.file_field :image

    - @upload.errors.each do |attribute, error|
      .alert.alert-danger.alert-dismissable
        %button.close{type: 'button', 'data-dismiss' => 'alert', 'aria-hidden' => 'true'}
          &times;
        = attribute
        = error

    = f.submit 'Create'

app/views/uploads/show.html.haml
- title 'Image'

%ul.list-group
  %li.list-group-item.item-heading
    = "Image"
  %li.list-group-item.text-center
    = image_tag @upload.image.url(:original), class: 'img-rounded', style: 'max-width: 100%'

  - unless @upload.description.nil? or @upload.description.empty?
    %li.list-group-item.item-heading
      = "Description"
    %li.list-group-item.text-center
      = raw simple_format @upload.description

= link_to "Back to Advert", show_advert_path(@upload.advert), class: 'btn btn-default btn-sm pull-right'