config/routes.rb
Uctads::Application.routes.draw do

  # == categories routing ==
  get '/categories',          to: 'categories#index',   as: 'categories'
  get '/categories/new',      to: 'categories#new',     as: 'new_category'
  post '/categories',         to: 'categories#create',  as: 'create_category'
  get '/categories/:id',      to: 'categories#show',    as: 'show_category'
  get '/categories/:id/edit', to: 'categories#edit',    as: 'edit_category'
  patch '/categories/:id',    to: 'categories#update',  as: 'update_category'
  delete '/categories/:id',   to: 'categories#destroy', as: 'destroy_category'

  get '/categories/:id/ancestor_fields', to: 'categories#ancestor_fields'

  # == adverts routing ==
  get     '/adverts',                 to: 'adverts#index',              as: 'adverts'
  get     '/adverts_by_category/:id', to: 'adverts#index_by_category',  as: 'adverts_by_category'
  post    '/adverts',                 to: 'adverts#create',             as: 'create_advert'
  get     '/adverts/new',             to: 'adverts#new',                as: 'new_advert'
  get     '/adverts/:id',             to: 'adverts#show',               as: 'show_advert'
  get     '/adverts/:id/edit',        to: 'adverts#edit',               as: 'edit_advert'
  patch   '/adverts/:id',             to: 'adverts#update',             as: 'update_advert'
  delete  '/adverts/:id',             to: 'adverts#destroy',            as: 'destroy_advert'
  post    '/adverts/new_ad_form',     to: 'adverts#new_ad_form',        as: 'new_ad_form_advert'

  get     '/adverts/:id/gallery/edit',    to: 'adverts#edit_gallery',       as: 'edit_gallery'
  post    '/adverts/:id/gallery/upload', to: 'adverts#upload_to_gallery', as: 'upload_to_gallery'

  # == uploads routing ==
  get     '/uploads/:id',       to: 'uploads#show',     as: 'show_upload'
  get     '/uploads/:id/edit',  to: 'uploads#edit',     as: 'edit_upload'
  patch   '/uploads/:id',       to: 'uploads#update',   as: 'update_upload'
  delete  '/uploads/:id',       to: 'uploads#destroy',  as: 'destroy_upload'

  root 'adverts#index'


end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-dismissable #{ bootstrap_class_for(name) }"}
    %button.close{type: 'button', 'data-dismiss' => 'alert', 'aria-hidden' => 'true'}
      &times;
    = msg

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= "UCTads" + (content_for?(:title) ? " : #{yield(:title)}" : '')
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield(:head)
  %body
    #wrap
      %nav.navbar.navbar-inverse.navbar-fixed-top
        .container
          .navbar-header
            %button.navbar-toggle{ type: 'button', data: {target: '.navbar-collapse', toggle: 'collapse'} }
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{:href => "/"}
              %i.fa.fa-mortar-board
              = "UCTAds"
          .collapse.navbar-collapse
            = form_tag adverts_path, method: 'get', id: 'search-form', class: 'navbar-form navbar-left navbar-input-group custom-form-sm' do
              .form-group
                = text_field_tag :search, params[:search], size: 50, class: 'form-control input-sm', placeholder: 'Search ..'
                %button.btn.btn-info.btn-sm{type: 'submit'}= "Search"

            %ul.nav.navbar-nav
              %li.navbar-button-li
                = button_to "Post an Ad!", new_advert_path, method: :get, class: "btn btn-success btn-sm navbar-btn"

            %ul.nav.navbar-nav.navbar-right
              %li
                %a item
              %li
                %a item
      #page-wrap.container
        #content-wrap.content
          .row-fluid
            .col-sm-12
              = yield
          .clearfix
    #footer
      .container
        %p.text-center
          %small
            Copyright text and stuff

    %script{src: "http://maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"}